language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libgtest-dev
      - cmake
      - cmake-data

install:
  - mkdir ~/gtest
  - cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ /usr/src/gtest/
  - make
  - cd -

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./run_tests
