language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - cmake
      - cmake-data
      - gcc-6
      - g++-6

before_install:
  - pip install --user urllib3[secure] cpp-coveralls pyyaml

install:
  - export CC=gcc-6
  - export CXX=g++-6
  - mkdir ~/gtest
  - cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ /usr/src/gtest/
  - make
  - cd -

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./run_tests
  - cd -
  - coveralls --exclude lib --exclude tests --gcov gcov-6 --gcov-options '\-lp'
