language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
      - libgtest-dev

install:
  - mkdir ~/gtest
  - cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ /usr/src/gtest/
  - make
  - cd -

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./run_tests
